[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.filesystem = spiffs

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    links2004/WebSockets @ ^2.4.1
    emelianov/modbus-esp8266 @ ^4.1.0
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    esphome/AsyncTCP-esphome @ ^2.0.1

build_flags =
    -DCORE_DEBUG_LEVEL=3
